apiVersion: v1
kind: Service
metadata:
  name: flask-demo
spec:
  type: {{ .Values.service.type }}
  selector:
    app: flask-demo
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
